# Template de Projet Data - Exploration et Analyse
Ce notebook sert de structure de base pour tout projet d'exploration de données (EDA).

## 1. Importation des librairies et configuration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuration de l'affichage
pd.set_option('display.max_columns', None)
sns.set_theme(style="whitegrid")

## 2. Chargement des données

In [2]:
# Charger votre dataset ici
df_disponibilite = pd.read_csv('..\\Data\\Clean\\DF_DisponibiliteAlimentaire_2017.csv')
df_distance = pd.read_csv('..\\Data\\Clean\\DF_Distances.csv')
df_pib = pd.read_csv('..\\Data\\Clean\\DF_Pib_2017.csv')
df_stabilite = pd.read_csv('..\\Data\\Clean\\DF_Political_Stability_2017.csv')
df_population = pd.read_csv('..\\Data\\Clean\\DF_Population_2017.csv')
df_nourriture = pd.read_csv('..\\Data\\Clean\\DF_Nourriture_Quali_2017.csv')
df_business = pd.read_csv('..\\Data\\Clean\\DF_Business.csv')
df_Nourriture_Quali = pd.read_csv('..\\Data\\Clean\\DF_Nourriture_Quali_2017.csv')

In [3]:
df_disponibilite

,Unnamed: 0,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,nom_fr,country_en,iso2
0,0,Afghanistan,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,Afghanistan,Afghanistan,AF
1,1,Afrique du Sud,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,Afrique du Sud,South Africa,ZA
2,2,Albanie,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,Albanie,Albania,AL
3,3,Algérie,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,Algérie,Algeria,DZ
4,4,Allemagne,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,Allemagne,Germany,DE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,167,Émirats arabes unis,43.47,412.0,94.0,433.0,412.0,48.0,United Arab Emirates,ARE,Émirats arabes unis,United Arab Emirates,AE
168,168,Équateur,19.31,341.0,0.0,0.0,324.0,340.0,Ecuador,ECU,Équateur,Ecuador,EC
169,169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,18100.0,21914.0,United States,USA,États-Unis d'Amérique,United States of America,US
170,170,Éthiopie,0.13,14.0,NaN,1.0,14.0,14.0,Ethiopia,ETH,Éthiopie,Ethiopia,ET
171,171,Îles Salomon,4.45,3.0,0.0,6.0,3.0,0.0,Solomon Islands,SLB,Îles Salomon,Solomon Islands,SB

In [4]:
df_distance.head()

  Country Code  Distance en KM Country Name       nom_fr   country_en iso2
0          ABW        7685.884        Aruba        Aruba        Aruba   AW
1          AFG        5590.381  Afghanistan  Afghanistan  Afghanistan   AF
2          AGO        6510.322       Angola       Angola       Angola   AO
3          AIA        6710.570          NaN          NaN          NaN  NaN
4          ALB        1603.534      Albania      Albanie      Albania   AL

In [5]:
df_merged = pd.merge(df_disponibilite, df_distance[['Country Code', 'Distance en KM']], on='Country Code', how="left")

In [6]:
df_merged

,Unnamed: 0,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,nom_fr,country_en,iso2,Distance en KM
0,0,Afghanistan,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,Afghanistan,Afghanistan,AF,5590.3810
1,1,Afrique du Sud,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,Afrique du Sud,South Africa,ZA,9353.5520
2,2,Albanie,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,Albanie,Albania,AL,1603.5340
3,3,Algérie,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,Algérie,Algeria,DZ,1340.3900
4,4,Allemagne,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,Allemagne,Germany,DE,439.8984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,167,Émirats arabes unis,43.47,412.0,94.0,433.0,412.0,48.0,United Arab Emirates,ARE,Émirats arabes unis,United Arab Emirates,AE,5249.5350
168,168,Équateur,19.31,341.0,0.0,0.0,324.0,340.0,Ecuador,ECU,Équateur,Ecuador,EC,9367.0980
169,169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,18100.0,21914.0,United States,USA,États-Unis d'Amérique,United States of America,US,5838.1570
170,170,Éthiopie,0.13,14.0,NaN,1.0,14.0,14.0,Ethiopia,ETH,Éthiopie,Ethiopia,ET,5582.5020
171,171,Îles Salomon,4.45,3.0,0.0,6.0,3.0,0.0,Solomon Islands,SLB,Îles Salomon,Solomon Islands,SB,15178.2000

In [7]:
df_pib.head()

          Zone Country Code  PIB par habitant Country Name
0        Aruba          ABW      37524.914920        Aruba
1  Afghanistan          AFG       2335.795862  Afghanistan
2       Angola          AGO       8006.836615       Angola
3      Albania          ALB      14110.683242      Albania
4      Andorra          AND      53084.863964      Andorra

In [8]:
df_merged2 = pd.merge(df_merged,df_pib [['PIB par habitant','Country Code']], on='Country Code', how='left')

In [9]:
df_merged2.head()

,Unnamed: 0,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,nom_fr,country_en,iso2,Distance en KM,PIB par habitant
0,0,Afghanistan,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,Afghanistan,Afghanistan,AF,5590.3810,2335.795862
1,1,Afrique du Sud,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,Afrique du Sud,South Africa,ZA,9353.5520,13738.438585
2,2,Albanie,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,Albanie,Albania,AL,1603.5340,14110.683242
3,3,Algérie,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,Algérie,Algeria,DZ,1340.3900,13493.560749
4,4,Allemagne,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,Allemagne,Germany,DE,439.8984,54110.253665

In [10]:
df_stabilite.head()

,Country Code,Indice de stabilité politique,nom_fr,country_en,iso3,iso2
0,AFG,-2.61393089999999,Afghanistan,Afghanistan,AFG,AF
1,ALB,0.1638298,Albanie,Albania,ALB,AL
2,DZA,-0.929504599999999,Algérie,Algeria,DZA,DZ
3,ASM,1.2555945,NaN,NaN,NaN,NaN
4,AND,1.3250909,NaN,NaN,NaN,NaN

In [11]:
df_merged3 = pd.merge(df_merged2,df_stabilite [['Indice de stabilité politique','Country Code']], on='Country Code', how='left').reset_index(drop=True)

In [12]:
df_merged3 = df_merged3.dropna(subset=["Country Name"])

In [13]:
df_merged3.head()

,Unnamed: 0,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,nom_fr,country_en,iso2,Distance en KM,PIB par habitant,Indice de stabilité politique
0,0,Afghanistan,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,Afghanistan,Afghanistan,AF,5590.3810,2335.795862,-2.61393089999999
1,1,Afrique du Sud,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,Afrique du Sud,South Africa,ZA,9353.5520,13738.438585,-0.3828321
2,2,Albanie,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,Albanie,Albania,AL,1603.5340,14110.683242,0.1638298
3,3,Algérie,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,Algérie,Algeria,DZ,1340.3900,13493.560749,-0.929504599999999
4,4,Allemagne,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,Allemagne,Germany,DE,439.8984,54110.253665,0.7022243

In [14]:
# # voir si merge se fait sur Country Code ou left_on'Country Code', right_on='iso3'
df_merged4 = pd.merge(df_merged3,df_Nourriture_Quali [['Population pouvant acheter une alimentation saine (%)','Country Code']], on='Country Code', how='left')

In [15]:
df_merged5 = pd.merge(df_merged4,df_population [['Population','iso3']], left_on='Country Code',right_on='iso3', how='left').reset_index(drop=True)

In [16]:
df_Clean = pd.merge(df_merged5,df_business [['Taux de facilité de faire des affaires (%)','Country Code']], on='Country Code', how='left').reset_index(drop=True)

In [17]:
df_Clean

,Unnamed: 0,Zone,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,nom_fr,country_en,iso2,Distance en KM,PIB par habitant,Indice de stabilité politique,Population pouvant acheter une alimentation saine (%),Population,iso3,Taux de facilité de faire des affaires (%)
0,0,Afghanistan,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,Afghanistan,Afghanistan,AF,5590.3810,2335.795862,-2.61393089999999,NaN,36296000,AFG,37.13062
1,1,Afrique du Sud,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,Afrique du Sud,South Africa,ZA,9353.5520,13738.438585,-0.3828321,39.0,57009000,ZAF,65.32778
2,2,Albanie,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,Albanie,Albania,AL,1603.5340,14110.683242,0.1638298,75.7,2884000,ALB,66.8377
3,3,Algérie,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,Algérie,Algeria,DZ,1340.3900,13493.560749,-0.929504599999999,81.5,41389000,DZA,46.22686
4,4,Allemagne,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,Allemagne,Germany,DE,439.8984,54110.253665,0.7022243,97.3,82658000,DEU,79.34962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,167,Émirats arabes unis,43.47,412.0,94.0,433.0,412.0,48.0,United Arab Emirates,ARE,Émirats arabes unis,United Arab Emirates,AE,5249.5350,70281.888950,0.7192871,96.8,9487000,ARE,79.30036
167,168,Équateur,19.31,341.0,0.0,0.0,324.0,340.0,Ecuador,ECU,Équateur,Ecuador,EC,9367.0980,11793.479743,-0.1273984,76.9,16785000,ECU,57.49538
168,169,États-Unis d'Amérique,55.68,18266.0,3692.0,123.0,18100.0,21914.0,United States,USA,États-Unis d'Amérique,United States of America,US,5838.1570,60047.719073,0.1101294,95.0,325084000,USA,83.59008
169,170,Éthiopie,0.13,14.0,NaN,1.0,14.0,14.0,Ethiopia,ETH,Éthiopie,Ethiopia,ET,5582.5020,2004.747556,-1.5195725,40.7,106399000,ETH,46.14583
170,171,Îles Salomon,4.45,3.0,0.0,6.0,3.0,0.0,Solomon Islands,SLB,Îles Salomon,Solomon Islands,SB,15178.2000,2454.046719,0.1156377,NaN,636000,SLB,54.87857

In [18]:
df_Clean.drop(columns=['Unnamed: 0','Zone','nom_fr','country_en','iso2','iso3'], inplace=True)

In [19]:
df_Clean

,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Country Name,Country Code,Distance en KM,PIB par habitant,Indice de stabilité politique,Population pouvant acheter une alimentation saine (%),Population,Taux de facilité de faire des affaires (%)
0,1.53,57.0,NaN,29.0,55.0,28.0,Afghanistan,AFG,5590.3810,2335.795862,-2.61393089999999,NaN,36296000,37.13062
1,35.69,2118.0,63.0,514.0,2035.0,1667.0,South Africa,ZAF,9353.5520,13738.438585,-0.3828321,39.0,57009000,65.32778
2,16.36,47.0,0.0,38.0,47.0,13.0,Albania,ALB,1603.5340,14110.683242,0.1638298,75.7,2884000,66.8377
3,6.38,277.0,0.0,2.0,264.0,275.0,Algeria,DZA,1340.3900,13493.560749,-0.929504599999999,81.5,41389000,46.22686
4,19.47,1739.0,646.0,842.0,1609.0,1514.0,Germany,DEU,439.8984,54110.253665,0.7022243,97.3,82658000,79.34962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,43.47,412.0,94.0,433.0,412.0,48.0,United Arab Emirates,ARE,5249.5350,70281.888950,0.7192871,96.8,9487000,79.30036
167,19.31,341.0,0.0,0.0,324.0,340.0,Ecuador,ECU,9367.0980,11793.479743,-0.1273984,76.9,16785000,57.49538
168,55.68,18266.0,3692.0,123.0,18100.0,21914.0,United States,USA,5838.1570,60047.719073,0.1101294,95.0,325084000,83.59008
169,0.13,14.0,NaN,1.0,14.0,14.0,Ethiopia,ETH,5582.5020,2004.747556,-1.5195725,40.7,106399000,46.14583
170,4.45,3.0,0.0,6.0,3.0,0.0,Solomon Islands,SLB,15178.2000,2454.046719,0.1156377,NaN,636000,54.87857

In [20]:
df_Clean.insert(0, 'Zone', df_Clean.pop('Country Name'))
df_Clean.insert(1, 'Country Code', df_Clean.pop('Country Code'))

In [21]:
df_Clean.to_csv('..\\Data\\Clean\\DF_Clean.csv', index=False)

### Vérification de la validité des données

In [22]:
# Classement des pays par ordre décroissant de population
df_Clean = df_Clean.sort_values(by='Population', ascending=False)

# Calcul du cumul de la population
df_Clean['Cumul Population'] = df_Clean['Population'].cumsum()

In [23]:
df_Clean

,Zone,Country Code,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Distance en KM,PIB par habitant,Indice de stabilité politique,Population pouvant acheter une alimentation saine (%),Population,Taux de facilité de faire des affaires (%),Cumul Population
33,China,CHN,12.33,18161.0,576.0,452.0,17518.0,18236.0,8225.232,15022.437188,-0.203288,71.8,1421021000,64.20096,1421021000
65,India,IND,2.22,3661.0,4.0,0.0,2965.0,3545.0,6594.230,6144.717144,-0.572111399999999,30.5,1338676000,60.9076,2759697000
168,United States,USA,55.68,18266.0,3692.0,123.0,18100.0,21914.0,5838.157,60047.719073,0.1101294,95.0,325084000,83.59008,3084781000
66,Indonesia,IDN,7.19,2323.0,0.0,1.0,1904.0,2301.0,11584.250,10687.640922,-0.5816146,49.7,264650000,66.86799,3349431000
113,Pakistan,PAK,5.86,1282.0,4.0,2.0,1218.0,1281.0,5932.586,4789.536466,-2.2184098,42.2,207906000,53.01708,3557337000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,Grenada,GRD,45.70,8.0,NaN,7.0,5.0,1.0,7120.287,15041.452571,0.9134729,80.4,110000,53.30874,7344696000
133,St. Vincent and the Grenadines,VCT,72.31,8.0,NaN,9.0,8.0,0.0,6989.701,13575.431977,0.7873576,NaN,109000,56.97521,7344805000
6,Antigua and Barbuda,ATG,54.10,7.0,0.0,7.0,5.0,0.0,6708.770,21422.002158,0.614623,NaN,95000,59.79669,7344900000
43,Dominica,DMA,35.19,4.0,0.0,4.0,3.0,0.0,6826.396,12696.195661,1.1093885,NaN,71000,61.66778,7344971000
132,St. Kitts and Nevis,KNA,55.77,4.0,0.0,4.0,3.0,0.0,6760.687,29578.631163,0.6612426,NaN,52000,54.60143,7345023000

## 3. Inspection initiale et Nettoyage
- Vérification des types de données
- Identification des valeurs manquantes et doublons

In [24]:
print(df_Clean.info())
print("\nDoublons :", df_Clean.duplicated().sum())
print("\nValeurs manquantes :\n", df_Clean.isna().sum())

<class 'pandas.DataFrame'>
Index: 171 entries, 33 to 132
Data columns (total 15 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Zone                                                    171 non-null    str
 1   Country Code                                            171 non-null    str
 2   Disponibilité alimentaire en quantité (kg/personne/an)  171 non-null    float64
 3   Disponibilité intérieure                                169 non-null    float64
 4   Exportations - Quantité                                 134 non-null    float64
 5   Importations - Quantité                                 169 non-null    float64
 6   Nourriture                                              169 non-null    float64
 7   Production                                              167 non-null    float64
 8   Distance en KM                                          167 non-null    float64
 9   PIB par habitant                                        165 non-null    float64
 10  Indice de stabilité politique                           171 non-null    str
 11  Population pouvant acheter une alimentation saine (%)   139 non-null    float64
 12  Population                                              171 non-null    int64
 13  Taux de facilité de faire des affaires (%)              165 non-null    str
 14  Cumul Population                                        171 non-null    int64
dtypes: float64(9), int64(2), str(4)
memory usage: 26.6 KB
None

Doublons : 0

Valeurs manquantes :
 Zone                                                       0
Country Code                                               0
Disponibilité alimentaire en quantité (kg/personne/an)     0
Disponibilité intérieure                                   2
Exportations - Quantité                                   37
Importations - Quantité                                    2
Nourriture                                                 2
Production                                                 4
Distance en KM                                             4
PIB par habitant                                           6
Indice de stabilité politique                              0
Population pouvant acheter une alimentation saine (%)     32
Population                                                 0
Taux de facilité de faire des affaires (%)                 6
Cumul Population                                           0
dtype: int64

In [25]:
df_Clean = df_Clean.dropna()

In [26]:
df_Clean

,Zone,Country Code,Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Distance en KM,PIB par habitant,Indice de stabilité politique,Population pouvant acheter une alimentation saine (%),Population,Taux de facilité de faire des affaires (%),Cumul Population
33,China,CHN,12.33,18161.0,576.0,452.0,17518.0,18236.0,8225.2320,15022.437188,-0.203288,71.8,1421021000,64.20096,1421021000
65,India,IND,2.22,3661.0,4.0,0.0,2965.0,3545.0,6594.2300,6144.717144,-0.572111399999999,30.5,1338676000,60.9076,2759697000
168,United States,USA,55.68,18266.0,3692.0,123.0,18100.0,21914.0,5838.1570,60047.719073,0.1101294,95.0,325084000,83.59008,3084781000
66,Indonesia,IDN,7.19,2323.0,0.0,1.0,1904.0,2301.0,11584.2500,10687.640922,-0.5816146,49.7,264650000,66.86799,3349431000
113,Pakistan,PAK,5.86,1282.0,4.0,2.0,1218.0,1281.0,5932.5860,4789.536466,-2.2184098,42.2,207906000,53.01708,3557337000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Luxembourg,LUX,18.33,11.0,1.0,11.0,11.0,0.0,289.1023,114985.842236,1.2715421,97.4,591000,69.58844,7339636000
144,Suriname,SUR,31.06,25.0,5.0,18.0,18.0,10.0,7196.9870,17567.680240,0.1667453,80.4,570000,47.40665,7340206000
93,Malta,MLT,27.17,14.0,0.0,9.0,12.0,4.0,1752.6930,45763.733059,1.082828,95.5,437000,65.21409,7341676000
17,Belize,BLZ,25.69,19.0,0.0,0.0,10.0,20.0,8664.4390,9120.653383,0.0274572,34.4,375000,55.27374,7342432000
70,Iceland,ISL,29.95,10.0,0.0,2.0,10.0,10.0,2234.7230,55638.492059,1.2503574,99.4,334000,78.99464,7342766000

In [27]:
# Population mondiale totale en 2017 : 7_548_017_000 habitants
# Population totale en 2017 afin de vérifier que mon échantillon final représentera au moins 60 % de la population mondiale
# --> Population minimale : 4 528 810 200 habitants
# pop_totale_mondiale = df_Pop['Valeur'].sum()
# print(f"Population mondiale totale en 2017 : {pop_totale_mondiale:_.0f} habitants")

In [28]:
total_pop=df_Clean['Population'].sum()
print(total_pop)

6343171000

In [29]:
df_Clean.dropna()['Population'].sum() / df_population['Population'].sum() * 100

np.float64(84.03758232129049)

## 4. Exportation des données nettoyées

In [30]:
# Sauvegarde du dataframe final
df_Clean.to_csv('..\\Data\\Clean\\Final\\DF_Clean.csv', index=False)